### ISSUE TITLE
using plugins: mongoose-paginate

### ISSUE THREAD

**Issue by kerolloz** [typegoose/typegoose#219]
I am trying to use the [paginate](https://www.npmjs.com/package/mongoose-paginate-v2) plugin but I don't get IntelliSense for the `paginate()` method provided by this plugin. Typescript complains about paginate() method `Property 'paginate' does not exist on type 'ReturnModelType<typeof Dummy, unknown>'`. Though, it works after transpilation. 

```ts
import { Typegoose, plugin } from '@typegoose/typegoose';
import { FilterQuery, PaginateOptions, PaginateResult } from 'mongoose';
import mongoosePaginate from 'mongoose-paginate-v2';

@plugin(mongoosePaginate)
export class Dummy {
  @prop()
  name!: string;
}
```

I tried this solution https://github.com/szokodiakos/typegoose/issues/63. It somehow worked but it gives deprecation warning 
`(node:15629) DeprecationWarning: The Typegoose Class is deprecated, please try to remove it`. 
Anyway, It would be troublesome to add the paginate method every time I need to add pagination for a model.

## Versions

-    "@typegoose/typegoose": "^6.4.0",
-    "mongoose": "^5.9.7",

**Comment by kerolloz** [comment]
This solution worked for me

```ts
import mongoosePaginate from 'mongoose-paginate-v2';
import { JoiObjectId } from '../core/validations';
import { FilterQuery, PaginateOptions, PaginateResult } from 'mongoose';

type PaginateMethod<T> = (
  query?: FilterQuery<T>,
  options?: PaginateOptions,
  callback?: (err: any, result: PaginateResult<T>) => void,
) => Promise<PaginateResult<T>>;

@plugin(mongoosePaginate)
@modelOptions({
  schemaOptions: { timestamps: true, toJSON: { versionKey: false } },
})
export class Dummy {
  @prop()
  name!: string;

  @prop()
  photo!: string;

  @prop()
  cover!: string;

  @prop()
  description?: string;

  static paginate: PaginateMethod<Dummy>;
}
```

**Comment by hasezoey** [comment]
> It somehow worked but it gives deprecation warning

you extended the deprecated (and useless) `Typegoose` class

---

from what i read, this issue is solved

**Comment by kerolloz** [comment]
@hasezoey 

why should I add the static method every time?
I believe the `@plugin()` decorator should be responsible for that.

**Comment by hasezoey** [comment]
@kerolloz an decorator cant add an type, so you either need to do it for every class, or extend an class that has it defined

**Comment by kerolloz** [comment]
The problem with this approach is I still don't get IntelliSense until I write the static method again in the subclass.

```ts
import { plugin } from '@typegoose/typegoose';
import mongoosePaginate from 'mongoose-paginate-v2';
import { PaginateMethod } from '../core/models';
import { BaseModel } from './BaseModel';

@plugin(mongoosePaginate)
export abstract class PaginatedModel extends BaseModel {
  static paginate: PaginateMethod<PaginatedModel>;
}

export class Dummy extends PaginatedModel {
  @prop()
  name!: string;

  static paginate: PaginateMethod<Dummy>; // have to be repeated
}

```

**Comment by hasezoey** [comment]
functions that have just an type in an abstract class need to be implemented by all child classes 

it should work when you just remove the `abstract` keyword (the class will persist anyway)

**Comment by simoazzo** [comment]
> This solution worked for me
> 
> ```ts
> import mongoosePaginate from 'mongoose-paginate-v2';
> import { FilterQuery, PaginateOptions, PaginateResult } from 'mongoose';
> 
> type PaginateMethod<T> = (
>   query?: FilterQuery<T>,
>   options?: PaginateOptions,
>   callback?: (err: any, result: PaginateResult<T>) => void,
> ) => Promise<PaginateResult<T>>;
> 
> @plugin(mongoosePaginate)
> export class Dummy {
>   @prop()
>   name!: string;
> 
>   static paginate: PaginateMethod<Dummy>;
> }
> ```

Do you have a working example please? I mean the Dummy being used with pagination?

**Comment by kerolloz** [comment]
```ts
import { plugin } from '@typegoose/typegoose';
import { FilterQuery, PaginateOptions, PaginateResult } from 'mongoose';
import mongoosePaginate from 'mongoose-paginate-v2';
import BaseModel from './BaseModel';
 
@plugin(mongoosePaginate)
export default class PaginatedModel extends BaseModel {
  static paginate: <T extends PaginatedModel>(
    this: T,
    query?: FilterQuery<T>,
    options?: PaginateOptions,
    callback?: (err: Error, result: PaginateResult<T>) => void,
  ) => Promise<PaginateResult<T>>;
}

const result = await PaginatedModel.paginate({ query: "abc" });
```
  @simoazzo
Do you have a problem with the provided example?

**Comment by kerolloz** [comment]
You can use the `PaginatedModel` class as the base class and you just have to extend it to provide pagination for new models. 

```ts
export class MyModel extends PaginatedModel {
  @prop({ required: true })
  name!: string;
}
```
Now you can use `MyModel` easily. 

```ts
MyModel.paginate({ name: "Kerollos" })
```

**Comment by jordiyapz** [comment]
This worked for me:

```typescript
import { plugin } from '@typegoose/typegoose';
import mongoosePaginate from 'mongoose-paginate-v2';
import mongoose from 'mongoose';

@plugin(mongoosePaginate)
export default class PaginatedClass {
  static paginate: mongoose.PaginateModel<typeof PaginatedClass>['paginate']
}

const PaginatedModel = getModelForClass(PaginatedClass);

const result = await PaginatedModel.paginate({ query: "abc" });
```

**Comment by mowaleed96** [comment]
> You can use the `PaginatedModel` class as the base class and you just have to extend it to provide pagination for new models.
> 
> ```ts
> export class MyModel extends PaginatedModel {
>   @prop({ required: true })
>   name!: string;
> }
> ```
> 
> Now you can use `MyModel` easily.
> 
> ```ts
> MyModel.paginate({ name: "Kerollos" })
> ```

For anyone using typescript, unfortunately, extending `PaginatedClass`  will not work with typescript as the returned docs would be of type `PaginatedClass` not the `MyModel`
So any one using type script needs to do type casting.
